const productosb = [
    {
      nombre: "Frankenstrat",
      descripcion: "La icónica guitarra modificada por Eddie Van Halen.",
      c1: "Cuerpo estilo Stratocaster",
      c2: "Pintura roja con rayas blancas y negras",
      c3: "Pastilla humbucker en el puente",
      c4: "Golpeador parcial negro",
      c5: "Mástil de arce con diapasón de una pieza",
      c6: "Puente Floyd Rose con trémolo",
      c7: "Control de volumen único (sin tono)",
      c8: "Cinta adhesiva para el diseño de rayas",
      c9: "Cabezal sin logo de Fender",
      c10: "Placa de cuello con el número 61071",
      c11: "Cables internos visibles por la falta de golpeador",
      c12: "Selector de pastillas atornillado sin función",
      c13: "Cuerpo de fresno con cavidades hechas a mano",
      c14: "Trastes jumbo para mayor facilidad de ejecución",
      c15: "Tuerca de latón para mejorar la resonancia",
  },
  {
    nombre: "Red Special",
    descripcion: "Guitarra hecha a mano por Brian May y su padre.",
    c1: "Construida con madera de una chimenea",
    c2: "Mástil de caoba con diapasón de ébano",
    c3: "Pastillas Burns Tri-Sonic modificadas",
    c4: "Trémolo casero con resortes de moto",
    c5: "Cuerpo hueco con cámaras de resonancia",
    c6: "Selector de fase individual por pastilla",
    c7: "Puente de aluminio hecho a mano",
    c8: "Golpeador negro personalizado",
    c9: "Clavijero con diseño único",
    c10: "Escala de 24 pulgadas",
    c11: "Acabado en color rojo con barniz casero",
    c12: "Afinadores Schaller",
    c13: "Cuerdas más gruesas para mayor sustain",
    c14: "Uso de una moneda en lugar de púa",
    c15: "Sonido distintivo con Vox AC30 y treble booster",
  },
  {
    nombre: "Gibson SG de Angus Young",
    descripcion: "El arma principal del guitarrista de AC/DC.",
    c1: "Cuerpo de caoba ultraligero",
    c2: "Mástil delgado y rápido",
    c3: "Pastillas humbucker de alto output",
    c4: "Golpeador grande estilo 'batwing'",
    c5: "Diapasón de palisandro con trapezoides",
    c6: "Puente Tune-O-Matic con stopbar",
    c7: "Afinadores Grover Deluxe",
    c8: "Selector de pastillas de tres posiciones",
    c9: "Perillas reflectantes vintage",
    c10: "Acabado en cereza oscuro",
    c11: "Clavijero inclinado para mayor sustain",
    c12: "Escala de 24.75 pulgadas",
    c13: "Uso intensivo del vibrato y bends",
    c14: "Famosa por su tono crudo y potente",
    c15: "Icónica con la vestimenta de colegial",
  },
  {
    nombre: "Gibson Les Paul de Slash",
    descripcion: "La guitarra emblemática de Guns N' Roses.",
    c1: "Cuerpo de caoba con tapa de arce",
    c2: "Mástil encolado de caoba",
    c3: "Pastillas Seymour Duncan Alnico II Pro",
    c4: "Diapasón de palisandro",
    c5: "Puente Tune-O-Matic con stopbar",
    c6: "Perillas doradas tipo top hat",
    c7: "Acabado en sunburst clásico",
    c8: "Selector de pastillas de tres posiciones",
    c9: "Trastes medium-jumbo",
    c10: "Clavijas vintage estilo Kluson",
    c11: "Escala de 24.75 pulgadas",
    c12: "Sonido grueso con mucho sustain",
    c13: "Uso frecuente del wah-wah",
    c14: "Siempre afinada en Eb estándar",
    c15: "Ícono del rock con su sombrero de copa",
  },
  {
    nombre: "Telecaster de Keith Richards",
    descripcion: "La 'Micawber', su icónica Tele de los Stones.",
    c1: "Cuerpo de fresno sólido",
    c2: "Mástil de arce grueso",
    c3: "Pastilla humbucker en el mástil",
    c4: "Pastilla single-coil en el puente",
    c5: "Golpeador negro de una sola capa",
    c6: "Puente vintage con 3 selletas de latón",
    c7: "Afinada en Open G",
    c8: "Cuerdas más gruesas en las primeras posiciones",
    c9: "Selector de pastillas de tres posiciones",
    c10: "Perillas tipo barril",
    c11: "Clavijero Fender con logo spaghetti",
    c12: "Acabado butterscotch blonde envejecido",
    c13: "Mástil sin la cuerda sexta (Mi grave)",
    c14: "Sonido rítmico y crujiente",
    c15: "Fundamental en el sonido de los Stones",
  }
  ]
  
  
  export default productosb