const productosb = [
    {
      nombre: "Frankenstrat",
      descripcion: "La icónica guitarra modificada por Eddie Van Halen.",
      c1: "Cuerpo estilo Stratocaster",
      c2: "Pintura roja con rayas blancas y negras",
      c3: "Pastilla humbucker en el puente",
      c4: "Golpeador parcial negro",
      c5: "Mástil de arce con diapasón de una pieza",
      c6: "Puente Floyd Rose con trémolo",
      c7: "Control de volumen único (sin tono)",
      c8: "Cinta adhesiva para el diseño de rayas",
      c9: "Cabezal sin logo de Fender",
      c10: "Placa de cuello con el número 61071",
      c11: "Cables internos visibles por la falta de golpeador",
      c12: "Selector de pastillas atornillado sin función",
      c13: "Cuerpo de fresno con cavidades hechas a mano",
      c14: "Trastes jumbo para mayor facilidad de ejecución",
      c15: "Tuerca de latón para mejorar la resonancia",
  },
  {
    nombre: "Red Special",
    descripcion: "Guitarra hecha a mano por Brian May y su padre.",
    c1: "Construida con madera de una chimenea",
    c2: "Mástil de caoba con diapasón de ébano",
    c3: "Pastillas Burns Tri-Sonic modificadas",
    c4: "Trémolo casero con resortes de moto",
    c5: "Cuerpo hueco con cámaras de resonancia",
    c6: "Selector de fase individual por pastilla",
    c7: "Puente de aluminio hecho a mano",
    c8: "Golpeador negro personalizado",
    c9: "Clavijero con diseño único",
    c10: "Escala de 24 pulgadas",
    c11: "Acabado en color rojo con barniz casero",
    c12: "Afinadores Schaller",
    c13: "Cuerdas más gruesas para mayor sustain",
    c14: "Uso de una moneda en lugar de púa",
    c15: "Sonido distintivo con Vox AC30 y treble booster",
  },
  {
    nombre: "Gibson SG de Angus Young",
    descripcion: "El arma principal del guitarrista de AC/DC.",
    c1: "Cuerpo de caoba ultraligero",
    c2: "Mástil delgado y rápido",
    c3: "Pastillas humbucker de alto output",
    c4: "Golpeador grande estilo 'batwing'",
    c5: "Diapasón de palisandro con trapezoides",
    c6: "Puente Tune-O-Matic con stopbar",
    c7: "Afinadores Grover Deluxe",
    c8: "Selector de pastillas de tres posiciones",
    c9: "Perillas reflectantes vintage",
    c10: "Acabado en cereza oscuro",
    c11: "Clavijero inclinado para mayor sustain",
    c12: "Escala de 24.75 pulgadas",
    c13: "Uso intensivo del vibrato y bends",
    c14: "Famosa por su tono crudo y potente",
    c15: "Icónica con la vestimenta de colegial",
  },
  {
    nombre: "Gibson Les Paul de Slash",
    descripcion: "La guitarra emblemática de Guns N' Roses.",
    c1: "Cuerpo de caoba con tapa de arce",
    c2: "Mástil encolado de caoba",
    c3: "Pastillas Seymour Duncan Alnico II Pro",
    c4: "Diapasón de palisandro",
    c5: "Puente Tune-O-Matic con stopbar",
    c6: "Perillas doradas tipo top hat",
    c7: "Acabado en sunburst clásico",
    c8: "Selector de pastillas de tres posiciones",
    c9: "Trastes medium-jumbo",
    c10: "Clavijas vintage estilo Kluson",
    c11: "Escala de 24.75 pulgadas",
    c12: "Sonido grueso con mucho sustain",
    c13: "Uso frecuente del wah-wah",
    c14: "Siempre afinada en Eb estándar",
    c15: "Ícono del rock con su sombrero de copa",
  },
  {
    nombre: "Telecaster de Keith Richards",
    descripcion: "La 'Micawber', su icónica Tele de los Stones.",
    c1: "Cuerpo de fresno sólido",
    c2: "Mástil de arce grueso",
    c3: "Pastilla humbucker en el mástil",
    c4: "Pastilla single-coil en el puente",
    c5: "Golpeador negro de una sola capa",
    c6: "Puente vintage con 3 selletas de latón",
    c7: "Afinada en Open G",
    c8: "Cuerdas más gruesas en las primeras posiciones",
    c9: "Selector de pastillas de tres posiciones",
    c10: "Perillas tipo barril",
    c11: "Clavijero Fender con logo spaghetti",
    c12: "Acabado butterscotch blonde envejecido",
    c13: "Mástil sin la cuerda sexta (Mi grave)",
    c14: "Sonido rítmico y crujiente",
    c15: "Fundamental en el sonido de los Stones",
  },
  {
    nombre: "Fender Stratocaster de John Frusciante",
    descripcion: "Una Stratocaster icónica con un sonido cálido y desgastado, utilizada por John Frusciante en los Red Hot Chili Peppers.",
    c1: "Modelo 1962 reissue",
    c2: "Cuerpo de aliso",
    c3: "Mástil de arce con diapasón de palisandro",
    c4: "Desgaste natural por el uso intenso",
    c5: "Pastillas single-coil vintage",
    c6: "Golpeador en color tortoise",
    c7: "Configuración SSS",
    c8: "Trémolo sincronizado clásico",
    c9: "Potes y selectores originales de época",
    c10: "Tono cálido y cristalino",
    c11: "Afinada medio tono abajo (Eb)",
    c12: "Usada en álbumes clave como 'Californication' y 'By the Way'",
    c13: "Cables y circuitos modificados para mayor sensibilidad",
    c14: "Estilo de toque expresivo y dinámico",
    c15: "Sonido inconfundible en solos y acordes limpios"
  },
  {
    nombre: "ESP MX-220 'EET FUK' de James Hetfield",
    descripcion: "Una de las guitarras más icónicas de James Hetfield, utilizada en la era '...And Justice for All', con su distintivo sonido pesado y ataque agresivo.",
    c1: "Modelo ESP MX-220",
    c2: "Forma similar a la Gibson Explorer",
    c3: "Cuerpo de caoba",
    c4: "Mástil de caoba con diapasón de ébano",
    c5: "Inlays en forma de puntos",
    c6: "Pastillas EMG 81 activas",
    c7: "Acabado en blanco con envejecido natural",
    c8: "Pegatina 'EET FUK' en el cuerpo",
    c9: "Puente Tune-o-Matic con cordal fijo",
    c10: "Configuración de controles simple (volumen y tono)",
    c11: "Escala de 24.75 pulgadas",
    c12: "Usada en giras y grabaciones de Metallica",
    c13: "Sonido denso y con alto sustain",
    c14: "Afinada en tonos más bajos (D Standard y Drop C)",
    c15: "Clave en el sonido rítmico de Metallica"
  },
  {
    nombre: "Gibson ES-355 'Lucille' de B.B. King",
    descripcion: "La icónica guitarra de B.B. King, una Gibson ES-355 personalizada sin agujeros en 'f' y con un tono cálido y suave, ideal para el blues.",
    c1: "Modelo Gibson ES-355",
    c2: "Cuerpo semi-hueco de arce y caoba",
    c3: "Sin agujeros en 'f' para evitar feedback",
    c4: "Mástil de caoba con diapasón de ébano",
    c5: "Inlays en bloque",
    c6: "Pastillas humbucker Gibson 490R/490T",
    c7: "Selector Varitone de seis posiciones",
    c8: "Puente Tune-o-Matic con cordal TP-6",
    c9: "Acabado en negro brillante",
    c10: "Golpeador dorado y herrajes dorados",
    c11: "Firma de B.B. King en el clavijero",
    c12: "Tono cálido con sustain prolongado",
    c13: "Afinada en estándar (EADGBE)",
    c14: "Usada en éxitos como 'The Thrill Is Gone'",
    c15: "Sonido limpio y expresivo para el blues"
  }

  ]
  
  
  export default productosb